language: c
compiler:
- gcc
env:
  global:
  - secure: AgDJV7/ubjxZFcxuOlkOizWyo0VLve9Pdh5Xz+3Ec37SeYotfUWAupwMZdMXZdKiDyHkAo1R0GdHgpkJ+Tm12o8WdsxZvTi0JdNtXObrYstNnzleuzf9fTsaY74wRDC2Q2URhBrR+oNcD19Lp6mpoCk6asDBhn2+6CP+dLBtKOE= 
  - secure: Tp53B4vuTKhpMsyAFr5zIHzWtD9XoeLS4CzW3bSgUpuzdHUD+SVunwnjileleKzLY6Iqf3v02NK/TqGDNpehdlWGQf9TgSLSqG0GMohLUaipuVj6HS6LD0vAgU+3U1TdBfvDelDIppqK2CCph2g5Vtw0OXvopw6HQdXeBDSOUKE=
addons:
  coverity_scan:
    project:
      name: acplt/open62541
      description: Open-source OPC UA
    notification_email: 
    build_command_prepend: ./autogen.sh && ./configure
    build_command: make
    branch_pattern: coverity_scan
before_install:
- sudo add-apt-repository ppa:libreoffice/ppa -y
- sudo apt-get update -qq
- sudo apt-get install -qq build-essential subversion git autoconf libtool texinfo
  python-lxml graphviz doxygen
- svn checkout https://svn.code.sf.net/p/check/code/trunk check-code
- cd check-code
- autoreconf --install
- ./configure
- make
- sudo make install
- sudo ldconfig
- cd ..
- rm -rf check-code
script: ./autogen.sh && ./configure --enable-doxygen && make && make check
after_success:
   - git clone -b gh-pages https://$GITAUTH@github.com/acplt/open62541
   - rm -rf open62541/doxygen
   - cp -r doc/html open62541/doxygen
   - cd open62541/doxygen
   - git config --global user.email "open62541-travis-ci@users.noreply.github.com"
   - git config --global user.name "Open62541 travis-ci"
   - git config --global push.default simple
   - git add *
   - git commit -am "doxygen updated by travis-ci"
   - git push https://$GITAUTH@github.com/acplt/open62541
   - cd ..
   - cd ..
   - rm -rf open62541
   - ./.coverity.sh
